# Site settings
title: decent.im
# email:
description: "Decent Jabber public service"
baseurl: ""
url: "https://decent-im.github.io"
github_username:  decent-im

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

paginate: 5

gems:
  - jekyll-sitemap
